# Generated by Django 2.1.5 on 2019-01-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='upeate_at',
            new_name='update_at',
        ),
    ]
